### ISSUE TITLE
Use mkdtemp instead of tempnam

### ISSUE THREAD

**Issue by bartblaze** [tylabs/quicksand_lite#3]
remnux@remnux:~/quicksand_lite$ ./build.sh 
> /tmp/ccNGE0oB.o: In function `quicksand_extract_zlib78':
> /home/remnux/quicksand_lite/libqs.c:1130: warning: the use of `tempnam' is dangerous, better use `mkstemp'

Better to use mkdtemp to avoid these warnings, if possible.

**Comment by tylabs** [comment]
The temporary file pointers are required for inflate - I'll look into converting that to buffers in memory instead.

**Comment by tylabs** [comment]
Additional dependancies with libzip - updated libzip requirements to a more recent version which allows in memory processing. All tempnam references/temp file usage removed which should speed things up as well.
